### ISSUE TITLE
There is a bug in REST API

### ISSUE THREAD

**Issue by GabeJonson** [OpenBeta/beta#9]
I try to send POST request via Postman, but responce is:
![postman response](https://cloud.githubusercontent.com/assets/7942725/23903843/929aeec4-08ce-11e7-9ea7-eb74348f19de.jpg)

**Comment by vietnugent** [comment]
it appears you were trying to connect to onesignal.com?  it's not our api server.

**Comment by GabeJonson** [comment]
Oops I'm sorry, my mistake...
